---
handlers:
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes

- name: restart apache
  service:
    name: httpd
    state: restarted
    enabled: yes

- name: systemd daemon reload
  systemd:
      daemon_reload: yes